config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'home#top'
  resources :users
  resources :events do
    resources :comments, only: :create
    resources :entries, only: [:index, :new, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  resources :notifications
  resources :relationships, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :room, optional: true
  belongs_to :message, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @notifications = current_user.passive_notifications.where(checked: false)
  end

  def update
    notifications=Notification.where(visitor_id: params[:visitor_id])
    if notifications.update_all(checked: true)
      hobby = Invite.where(user_id: params[:visitor_id]).map(&:room_id)
      current = Invite.where(user_id: current_user).map(&:room_id)
      set = hobby & current
      roomset = Room.find(set[0])
      redirect_to room_path(roomset.id) 
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<% if notification.checked == false %>
    <div class="border p-3">
        <%= link_to user_path(visitor) do %>
            <p><%= visitor.nickname %>さん
        <% end %>
        <% if notification.action=='dm' %>
        があなたにDMを送りました。<br>
        <small class="text-muted"><%= Message.find_by(id: notification.message_id)&.body %></small></p>
        <% end %>
        <%= link_to 'メッセージを確認する',notification_path(notification.id, visitor_id: visitor.id),method: :put %>
        
    </div>
<% end %>

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<div class="container">
<% if notifications.exists? %>
    <%= render @notifications %>
<% else %>
    <p class="border p-3">※通知はございません</p>
<% end %>
</div>