config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'home#top'
  resources :users
  resources :events do
    resources :comments, only: :create
    resources :entries, only: [:index, :new, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  resources :notifications
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/
         validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX, message: "は半角6~12文字英大文字・小文字・数字それぞれ１文字以上含む必要があります"}, on: :create

         has_many :events, dependent: :destroy
         has_many :entries, dependent: :destroy
         has_many :entried_events,  source: :event, through: :entries
         has_many :comments, dependent: :destroy
         has_many :messages, dependent: :destroy
         has_many :room_users, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_one_attached :user_image
         
         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

         has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
         has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

          def already_favorited?(event)
            self.favorites.exists?(event_id: event.id)
          end

          with_options presence: true do
          validates :nickname
          validates :school_year
          validates :undergraduate
          validates :student_nunber
          end
          validates :profile, length: { maximum: 250 }
          validates :student_nunber, length: { is: 10 }, uniqueness: true

          def self.guest
            find_or_create_by!(email: 'guest@example.com') do |user|
              user.password = 'Guests123'
              user.password_confirmation = user.password
              user.nickname = 'ゲストユーザー'
              user.school_year = '1回生'
              user.undergraduate = '経営学部'
              user.student_nunber = "2134567809"
              user.profile = 'ゲストユーザーです。'
            end
          end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: [:update, :destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :move_to_index_user, only: [:edit]

  def index
    @users = User.all
  end

  def show
    @events = Event.all
    @entry_events = @user.entried_events
    @entries = Entry.all
    @currentUserInvite = Invite.where(user_id: current_user.id)
    @userInvite = Invite.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg =""
    else
      @currentUserInvite.each do |cu|
        @userInvite.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom != true
        @room = Room.new
        @invite = Invite.new
      end

    end
  end

  def edit
  end

  def update
    if  @user.update(user_params)
      redirect_to user_path(@user), notice: '更新に成功しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :user_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index_user
    if @user != current_user
      redirect_to root_path, alert: '不正なアクセスです。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>ユーザー編集ページ</em></b></h4>
  </div>
</div>
<% if @user.errors.any? %>
  <div>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
<%= form_for @user do |f| %>
  
  <div class="field mt-3">
    <b><%= f.label :username, "ニックネーム" , class: "my-2" %></b><br />
    <i class="fas fa-user"></i>
    <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", placeholder: "nickname", class: "form-control" %>
  </div>

  <div class="field mt-2">
    <b><%= f.label :email, "Eメールアドレス" , class: "my-2"%></b><br />
    <i class="far fa-envelope"></i>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "email", class: "form-control"%>
  </div>

      <div class="field mt-3">
    <b><%= f.label :school_year, '学年', class: "my-2" %></b><br />
    <i class="fas fa-graduation-cap"></i>
    <%= f.select :school_year, {'1回生': '1回生', '2回生': '2回生', '3回生': '3回生', '4回生': '4回生', '院生': '院生'}, { include_blank: '学年を選択してください'}, { class: 'form-control' , required: true } %>
    </div>

    <div class="field mt-3">
    <b><%= f.label :undergraduate, '学部', class: "my-2" %></b><br />
    <i class="fas fa-graduation-cap"></i>
    <%= f.select :undergraduate, {'法学部': '法学部', '経済学部': '経済学部', '経営学部': '経営学部', '理工学部': '理工学部', '建築学部': '建築学部', '薬学部': '薬学部', '文芸学部': '文芸学部', '総合社会学部': '総合社会学部', '国際学部': '国際学部', '農学部': '農学部', '医学学部': '医学学部', '生物理工学部': '生物理工学部', '工学部': '工学部', '産業理工学部': '産業理工学部', '短期大学部': '短期大学学部', '通信教育部': '通信教育部'}, { include_blank: '学部を選択してください'}, { class: 'form-control' , required: true } %>
    </div>

  <div class="field mt-3">
    <b><%= f.label :student_nunber, "学籍番号" , class: "my-2" %></b><br />
    <i class="fas fa-user"></i>
    <%= f.number_field :student_nunber, autofocus: true, placeholder: "数字のみ入力", class: "form-control" %>
  </div>

  <b><%= f.label :profile, "プロフィール" , class: "my-2"%></b><br />
  <%= f.text_area :profile, placeholder: "プロフィール(250文字以内)", row: "10", class: "form-control" %>

  <b><%= f.label :user_image, "プロフィール画像", class: "my-2"  %></b><br />
  <%= f.file_field :user_image, class: 'hidden' %>

<div class="actions mt-4">
  <%= f.submit "更新" , class: "btn btn-primary col-4 offset-4"%>
</div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>ユーザー一覧</em></b></h4>
  </div>
</div>


  <div class="container">
    <div class="row">
      <% @users.each do |user| %>
        <div class="card mt-5 border-4 mx-auto" style="width: 20rem;">
          <%= link_to user_path(user) do %>
          <% if user.user_image.attached? %>
            <%= image_tag user.user_image, class: "card-img-top mt-3" %>    
          <% else %>
            <%= image_tag("no-user-image.jpg", class: "card-img-top") %>
          <% end %>
        <% end %>
            <div class="card-body border-top border-2 mt-2 ">
              <p class="card-text h2 border-2 pb-2 border-bottom"><%= link_to user.nickname, user_path(user), class: "text-decoration-none" %></p>
              <p><%= user.undergraduate %><span class="ms-3"><%= user.school_year %></span></p>
              <p class="border p-1"><b>プロフィール：</b><br><%= user.profile %></p>
              <p>投稿数:<%= user.events.count %></p>
            </div>
            <p><%= link_to 'ユーザーページへ', user_path(user.id) %></p>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>ユーザー詳細ページ</em></b></h4>
  </div>
</div>

<div class="container">
  <div class="myprofile row border border-3 w-50 mx-auto p-2 mt-2">
    <ul class="d-flex list-unstyled">
      <li class="text-start">
          <% if @user.user_image.attached? %>
            <%= image_tag @user.user_image, class: "card-img-top img-thumbnail w-50" %>    
          <% else %>
            <%= image_tag("no-user-image.jpg", class: "card-img-top w-50") %>
          <% end %>
        <h3 class="text-start mt-3"><%= @user.nickname %></h3><%= @user.undergraduate %><span class="ms-3"><%= @user.school_year %></span>
        <div class="user-in">
          <% if @user.id == current_user.id %>
            <%= @msg %>
          <% else %>

            <% if @isRoom == true %>
              <%= link_to room_path(@roomId) do %>
              <button type="button" class="btn btn-light border border-dark mt-3">DMを開始する</button>
              <% end %>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @invite do |e|%>
                  <% e.hidden_field :user_id, value: @user.id %>
                <% end %>
                <p class="mt-2">
                <%= f.submit "DMルームを作成する"%>
                </p>
              <% end %>
            <% end %>
            
          <% end %>
</div> 
        <% if @user.id == current_user.id %>
          <p class="mt-2">ID:<%= @user.email %></p>
        <% end %>
        </li>
        <li><span class="badge bg-dark">プロフィール</span>
        <% if @user.profile.blank? %>
          <div class="profile-box border border-dark rounded-3 p-2">プロフィールがありません。</div>
        <% else %>
          <div class="profile-box border border-dark rounded-3 p-2"><%= @user.profile %></div>
        <% end %>
        <% if @user.id == current_user.id %>
          <div class="mt-3"><%= link_to '編集', edit_user_path(@user), class: "btn btn-primary order-2" %>
          <%= link_to 'ログアウト', destroy_user_session_path , method: :delete , class: "btn border" %></div>
        <% end %>
        <div class="mt-5">
        <%= render 'relationships/follow_button', user: @user %>
        </div>
        <span class="me-3"><small class="text-muted">フォロー数：<%= @user.relationships.count %></small></span>
        <span><small class="text-muted">フォロワー数：<%= @user.followers.count %></small></span>
        
      </li>
    </ul>
  </div>
</div>

<% if @user.id == current_user.id %>
<div class="container border border-3 p-2 mt-3">
  <h3 class="mt-3">あなたがエントリー中のイベント</h3>
  <div class="row">
    <% @entry_events.each do |e_event| %>
      <div class="card mt-5 border mx-auto" style="width: 20rem;">
          <% if e_event.image.attached? %>
            <%= image_tag e_event.image, class: "card-img-top" %>
          <% else %>
            <%= image_tag("no-event-image.png", class: "card-img-top") %>
          <% end %>
            <div class="card-body border-bottom">
              <h5 class="card-title"><%= e_event.title %></h5>
            </div>
      <ul class="list-group list-group-flush border-bottom">
        <li class="list-group-item"><%= link_to event_path(e_event), class: "text-decoration-none text-dark" do %>
          <span class="card-text"><i class="fas fa-book"></i></span>このイベントを見る
          <% end %>
        </li>
      </ul>
        <p class="text-end"><time class="mh-100"><%= e_event.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新</p>
      </div>
    <% end %>
  </div>
</div>
<% end %>




<div class="container mt-3 border border-3 p-3">
<h3 class="mt-3">
    <% if @user.id == current_user.id %>
      あなたの投稿
    <% else %>
      <%= @user.nickname %>さんの投稿
    <% end %>
    </h3>
  <div class="row">
    <% @events.each do |event| %>
    <% if event.user_id == @user.id %>
      <div class="card mt-5 border mx-auto" style="width: 20rem;">
        <% if event.image.attached? %>
          <%= image_tag event.image, class: "card-img-top" %>
        <% else %>
          <%= image_tag("no-event-image.png", class: "card-img-top") %>
        <% end %>
            <div class="card-body border-bottom">
              <h5 class="card-title mt-3 border-top border-2 pt-3"><%= event.title %></h5>
              <p>エントリー者数：<%= event.entries.count %></p>
            </div>
      <ul class="list-group list-group-flush border-bottom">
        <li class="list-group-item"><%= link_to event_path(event), class: "text-decoration-none text-dark" do %>
          <span class="card-text"><i class="fas fa-book"></i></span>このイベントを見る
          <% end %>
        </li>
        <% if @user.id == current_user.id %>
        <li class="list-group-item"><%= link_to edit_event_path(event), class: "text-decoration-none text-dark" do %>
          <span class="card-text"><i class="fas fa-edit"></i></span>このイベントを編集する
          <% end %>
        </li>
        <li class="list-group-item"><%= link_to event_path(event), method: :delete, data: {confirm: "本当にこのイベントを削除しますか？"}, class: "text-decoration-none text-dark" do %>
            <span class="card-text"><i class="fas fa-trash-alt"></i></span>このイベントを削除する
          <% end %>
        </li>
      </ul>
          <% end %>
        <p class="text-end mt-1"><small><time class="mh-100"><%= event.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新</small></p>
      </div>
      <% end %>
    <% end %>
  </div>
</div>