config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'home#top'
  resources :users
  resources :events do
    resources :comments, only: :create
    resources :entries, only: [:index, :new, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  resources :notifications
  resources :relationships, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :activities_category
  belongs_to :event_prefecture
  belongs_to :people_number
  has_one_attached :image

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :title  
    validates :details
    validates :cost
    validates :event_date
    validates :start_time
    validates :end_time
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :activities_category_id
    validates :event_prefecture_id
    validates :people_number_id
  end
  validates :title , length: { maximum: 30 }
  validates :details, length: { maximum: 250 }
  validates :cost, numericality: { only_integer: true, greater_than: -1, less_than: 1000000 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: [:edit, :show]
  before_action :move_to_index_event, only: [:edit]
  before_action :search_product, only: [:index, :search]

  def index
    @events = Event.all
    @events = @p.result(distinct: true).order("created_at DESC")
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.valid?
      @event.save
      redirect_to event_path(@event), notice: 'イベント投稿に成功しました。'
    else
      render :new
    end
  end

  def show
    @entrys = Entry.all
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'イベントを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    @results = @p.result.order("created_at DESC")
  end

  private

  def event_params
    params.require(:event).permit(:title, :details, :category_id, :activities_category_id, :event_prefecture_id, :event_facility, :people_number_id, :cost, :event_date, :start_time, :end_time, :event_address, :image).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def move_to_index_event
    if @event.user_id != current_user.id 
      redirect_to root_path, alert: '不正なアクセスです。'
    end
  end

  def search_product
    @p = Event.ransack(params[:q])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>イベント編集ページ</em></b></h4>
  </div>
</div>


<div class="container">
<%= form_with(model: @event, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="field mt-3">
    <b><%= f.label :title, "タイトル" , class: "my-2" %></b><br/>
    <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "詳細情報" , class: "my-2" %></b><br/>
    <%= f.text_area :details, class:"form-control", placeholder:"詳細" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "ジャンル" , class: "my-2" %></b><br/>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>  
  <div class="field mt-3">
    <b><%= f.label :title, "開催地域" , class: "my-2" %></b><br/>
    <%= f.collection_select(:event_prefecture_id, EventPrefecture.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>

    <div class="field mt-3">
    <b><%= f.label :event_address, "開催住所" , class: "my-2" %></b><br/>
    <%= f.text_field :event_address, class:"form-control", placeholder:"開催住所" %>
  </div>
  
  <div class="field mt-3">
    <b><%= f.label :title, "参加可能人数" , class: "my-2" %></b><br/>
    <%= f.collection_select(:people_number_id, PeopleNumber.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "参加費用" , class: "my-2" %></b><br/>
    <%= f.text_field :cost, class: "form-control", placeholder: "※無料の場合は０と記入してください。" %>円
  </div>  
  <div class="field mt-3">
    <b><%= f.label :title, "開催日" , class: "my-2" %></b><br/>
    <%= f.date_field :event_date, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "開始時間" , class: "my-2" %></b><br/>
    <%= f.time_field :start_time, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "終了時間"  %></b><br/>
    <%= f.time_field :end_time, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :image, "イメージ画像", class: "me-5"  %></b>
    <%= f.file_field :image, class: 'hidden' %>
  </div>
    <%= f.submit "更新する" ,class: "btn btn-primary col-4 offset-4 my-3" %>
<% end %>
</div>

app/views/events/index.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>イベント一覧</em></b></h4>
  </div>
</div>

<div class="events-bg mt-5">
  <div class="container pb-3">
    <div class="row">
      <div class="seach1 border-5 rounded  col-6 mx-auto">
        <h5 class="search-text-1 mt-3 pb-2">イベント検索▼</h5>
        <%= search_form_for @p, url: search_events_path do |f| %>
          <%= f.label :title_cont, 'キーワード検索', class: "mt-2" %><i class="fas fa-search mx-1"></i>:
          <%= f.search_field :title_cont , class: "w-50 border-dark form-control" %>
        <br>
          <%= f.label :event_date_gteq, '開催日で絞り込む：' %>
          <%= f.date_field :event_date_gteq %>
        ~
          <%= f.date_field :event_date_lteq_end_of_day %>
        <br>
          <%= f.label :category_id_eq, 'カテゴリー:', class: "mt-2" %>
          <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :activities_category_id_eq, '活動目的:', class: "mt-2" %>
          <%= f.collection_select :activities_category_id_eq, ActivitiesCategory.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :event_prefecture_id_eq, '開催県：', class: "mt-2" %>
          <%= f.collection_select :event_prefecture_id_eq, EventPrefecture.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :cost, '価格：', class: "my-2" %>
          <%= f.radio_button :cost_lteq, '' %>
          指定なし
          <%= f.radio_button :cost_lteq, '0' ,class: "ms-2" %>
          無料
          <%= f.radio_button :cost_lteq, '500' ,class: "ms-2"  %>
          500円以内
          <%= f.radio_button :cost_lteq, '1000',class: "ms-2"  %>
          1000円以内
          <%= f.radio_button :cost_lteq, '1500',class: "ms-2"  %>
          1500円以内
          <br>
          <%= f.radio_button :cost_lteq, '2000',class: "ms-2"  %>
          2000円以内
          <%= f.radio_button :cost_lteq, '3000',class: "ms-2"  %>
          3000円以内
          <%= f.radio_button :cost_lteq, '4000',class: "ms-2"  %>
          4000円以内
          <%= f.radio_button :cost_lteq, '5000',class: "ms-2"  %>
          5000円以内
          <%= f.radio_button :cost_gteq, '5000',class: "ms-2"  %>
          5000円以上
        <br>
          <p class="mt-2"><%= f.submit '検索' ,class: "px-2 py-1 mx-2"%><%= link_to '絞り込みをクリア', events_path, class: "text-decoration-none text-dark border rounded border-dark p-1" %></p>
        <% end %>
      </div>

      <div class="row">
      <div class="p-2 mt-5 mx-auto col-7 border-top mb-2">
      <h5 class="mt-5 text-center">並び替え▼</h5>
      <thead>
        <tr>
          <th><span class="mx-1"><%= sort_link(@p, :category_id, "カテゴリー順" ) %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :event_prefecture_id, "都道府県順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :cost, "費用順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :event_date, "開催日順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :people_number_id, "参加人数順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :created_at, "投稿順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :user_id, "主催者別") %></span></th>
          <th><span class="mx-1"><%= link_to '元に戻す', events_path, class: "text-decoration-none text-dark border border-dark p-1" %></span></th>
        </tr>
      </thead>
      </div>
      </div>


      
      <% @events.each do |event| %>
        <div class="card mt-2 border border-3 mx-auto" style="width: 20rem;">
          <div class="article-text">
          <%= link_to event_path(event),class: "text-decoration-none text-dark border-top mt-3" do %>
          <% if event.image.attached? %>
            <%= image_tag event.image, class: "card-img-top" %>
          <% else %>
            <%= image_tag("no-event-image.png", class: "card-img-top") %>
          <% end %>
          </div>
          <div class="card-body">
            <h3 class="article-title">
              <%= event.title %>
            </h3>
            <div class="border rounded mt-3 p-3">
            <div class="article-title mt-1 border border-2 p-1 mb-2 rounded">
              活動目的：<br><%= event.activities_category.name %>
            </div>
            <div class="article-genre">
              ジャンル：<%= event.category.name %>
            </div>
            <div class="article-title mt-1">
              開催エリア：<%= event.event_prefecture.name %>
            </div>
            <div class="article-text mt-1">
              イベント日時：<%= event.event_date %>
            </div>
            <div class="article-text mt-1">
              主催者：<small><%= event.user.nickname %></small>
            </div>
            <div>  
              <time class="mh-100 mt-1">
                <small><%= event.updated_at.strftime("%Y-%m-%d %H:%M") %>
              </time>更新</small>
            </div>
            </div>
          </div>
          <% end %>

      <% if current_user %>
        <p>
          <% if current_user.already_favorited?(event) %>
            <%= link_to event_favorites_path(event),class: "text-decoration-none text-dark mt-3", method: :delete do %>
              <i class="fas fa-heart text-danger"></i>いいね！
            <% end %>
          <% else %>
            <%= link_to event_favorites_path(event),class: "text-decoration-none text-dark mt-3", method: :post do %>
              <i class="far fa-heart text-danger"></i>いいね！
            <% end %>
          <% end %>

        <%= event.favorites.count %></p>
      <% end  %>
      
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>イベント作成ページ</em></b></h4>
  </div>
</div>

<div class="container">
<%= form_with(model: @event, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="field mt-3">
    <b><%= f.label :title, "タイトル" , class: "my-2" %></b><br/>
    <%= f.text_field :title, class:"form-control", placeholder:"タイトル(30文字以内)" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "詳細情報" , class: "my-2" %></b><br/>
    <%= f.text_area :details, class:"form-control", placeholder:"詳細(250文字以内)" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "ジャンル" , class: "my-2" %></b><br/>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>  

  <div class="field mt-3">
    <b><%= f.label :activities_category_id, "活動目的" , class: "my-2" %></b><br/>
    <%= f.collection_select(:activities_category_id, ActivitiesCategory.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>  

  <div class="field mt-3">
    <b><%= f.label :title, "開催地域" , class: "my-2" %></b><br/>
    <%= f.collection_select(:event_prefecture_id, EventPrefecture.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>

    <div class="field mt-3">
    <b><%= f.label :event_address, "開催住所" , class: "my-2" %></b><br/>
    <%= f.text_field :event_address, class:"form-control", placeholder:"開催住所" %>
  </div>

      <div class="field mt-3">
    <b><%= f.label :event_facility, "開催施設名" , class: "my-2" %></b><br/>
    <%= f.text_field :event_facility, class:"form-control", placeholder:"開催施設名" %>
  </div>
  
  <div class="field mt-3">
    <b><%= f.label :title, "参加可能人数" , class: "my-2" %></b><br/>
    <%= f.collection_select(:people_number_id, PeopleNumber.all, :id, :name, {}, {class:"category-select form-control"}) %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "参加費用" , class: "my-2" %></b><br/>
    <%= f.number_field :cost, class: "form-control", placeholder: "※無料の場合は０と記入してください。" %>円
  </div>  
  <div class="field mt-3">
    <b><%= f.label :title, "開催日" , class: "my-2" %></b><br/>
    <%= f.date_field :event_date, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "開始時間" , class: "my-2" %></b><br/>
    <%= f.time_field :start_time, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :title, "終了時間"  %></b><br/>
    <%= f.time_field :end_time, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <b><%= f.label :image, "イメージ画像", class: "me-5"  %></b>
    <%= f.file_field :image, class: 'hidden' %>
  </div>
    <%= f.submit "投稿する" ,class: "btn btn-primary col-4 offset-4 my-3" %>
<% end %>
</div>

app/views/events/search.html.erb
<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>イベント一覧ページ</em></b></h4>
  </div>
</div>

<div class="events-bg mt-5">
  <div class="container pb-3">
    <div class="row">
      <div class="seach1 border-5 rounded  col-6 mx-auto">
        <h5 class="search-text-1 mt-3 pb-2">イベント検索▼</h5>
        <%= search_form_for @p, url: search_events_path do |f| %>
          <%= f.label :title_cont, 'キーワード検索', class: "mt-2" %><i class="fas fa-search mx-1"></i>:
          <%= f.search_field :title_cont , class: "w-50 border-dark form-control" %>
        <br>
          <%= f.label :event_date_gteq, '開催日で絞り込む：' %>
          <%= f.date_field :event_date_gteq %>
        ~
          <%= f.date_field :event_date_lteq_end_of_day %>
        <br>
          <%= f.label :category_id_eq, 'カテゴリー:', class: "mt-2" %>
          <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :activities_category_id_eq, '活動目的:', class: "mt-2" %>
          <%= f.collection_select :activities_category_id_eq, ActivitiesCategory.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :event_prefecture_id_eq, '開催県：', class: "mt-2" %>
          <%= f.collection_select :event_prefecture_id_eq, EventPrefecture.all, :id, :name, include_blank: '指定なし', class: "mt-2" %>
        <br>
          <%= f.label :cost, '価格：', class: "my-2" %>
          <%= f.radio_button :cost_lteq, '' %>
          指定なし
          <%= f.radio_button :cost_lteq, '0' ,class: "ms-2" %>
          無料
          <%= f.radio_button :cost_lteq, '500' ,class: "ms-2"  %>
          500円以内
          <%= f.radio_button :cost_lteq, '1000',class: "ms-2"  %>
          1000円以内
          <%= f.radio_button :cost_lteq, '1500',class: "ms-2"  %>
          1500円以内
          <br>
          <%= f.radio_button :cost_lteq, '2000',class: "ms-2"  %>
          2000円以内
          <%= f.radio_button :cost_lteq, '3000',class: "ms-2"  %>
          3000円以内
          <%= f.radio_button :cost_lteq, '4000',class: "ms-2"  %>
          4000円以内
          <%= f.radio_button :cost_lteq, '5000',class: "ms-2"  %>
          5000円以内
          <%= f.radio_button :cost_gteq, '5000',class: "ms-2"  %>
          5000円以上
        <br>
          <p class="mt-2"><%= f.submit '検索' ,class: "px-2 py-1 mx-2"%><%= link_to '絞り込みをクリア', events_path, class: "text-decoration-none text-dark border rounded border-dark p-1" %></p>
        <% end %>
      </div>

      <div class="row">
      <div class="p-2 mt-5 mx-auto col-7 border-top mb-2">
      <h5 class="mt-5 text-center">並び替え▼</h5>
      <thead>
        <tr>
          <th><span class="mx-1"><%= sort_link(@p, :category_id, "カテゴリー順" ) %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :event_prefecture_id, "都道府県順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :cost, "費用順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :event_date, "開催日順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :people_number_id, "参加人数順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :created_at, "投稿順") %></span></th>
          <th><span class="mx-1"><%= sort_link(@p, :user_id, "主催者別") %></span></th>
          <th><span class="mx-1"><%= link_to '元に戻す', events_path, class: "text-decoration-none text-dark border border-dark p-1" %></span></th>
        </tr>
      </thead>
      </div>
      </div>
<% if @results.length !=0 %>
      <% @results.each do |result| %>
        <div class="card mt-5 border border-3 mx-auto" style="width: 20rem;">
          <div class="article-text">
            <%= link_to event_path(result),class: "text-decoration-none text-dark border-top mt-3" do %>
          <% if result.image.attached? %>
            <%= image_tag result.image, class: "card-img-top" %>
          <% else %>
            <%= image_tag("no-event-image.png", class: "card-img-top") %>
          <% end %>
          </div>
          <div class="card-body">
            <h3 class="article-title">
              <%= result.title %>
            </h3>
            <div class="border border-2 rounded mt-3 p-3">
            <div class="article-title mt-1 border border-2 p-1 mb-2 rounded">
              活動目的：<br><%= result.activities_category.name %>
            </div>
            <div class="article-genre">
              ジャンル：<%= result.category.name %>
            </div>
            <div class="article-title mt-1">
              開催エリア：<%= result.event_prefecture.name %>
            </div>
            <div class="article-text mt-1">
              イベント日時：<%= result.event_date %>
            </div>
            <div class="article-text mt-1">
              主催者：<%= result.user.nickname %>
            </div>
            <div>
              <time class="mh-100 mt-1">
                <%= result.updated_at.strftime("%Y-%m-%d %H:%M") %>
              </time>更新
            </div>
            </div>
            </div>
            <% end %>

            <% if current_user %>
          <p>
          <% if current_user.already_favorited?(result) %>
            <%= link_to event_favorites_path(result),class: "text-decoration-none text-dark mt-3", method: :delete do %>
              <i class="fas fa-heart text-danger"></i>いいね！
            <% end %>
          <% else %>
            <%= link_to event_favorites_path(result),class: "text-decoration-none text-dark mt-3", method: :post do %>
              <i class="far fa-heart text-danger"></i>いいね！
            <% end %>
          <% end %>
          <%= result.favorites.count %>
          <% end  %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  該当するイベントはありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

app/views/events/show.html.erb
<div class="back-1">

<div class="top-title-box row border border-bottom">
  <div class="container my-auto">
    <h4 class="top-title text-center font-italic"><b><em>イベント詳細ページ</em></b></h4>
  </div>
</div>

<div class="container pb-5">
  <div class="event-card card mb-3 mt-5" style="max-width: 1500px;">
  <div class="row g-0 event-show-1">
    <div class="col-md-4">
    <% if @event.image.attached? %>
      <%= image_tag @event.image, class: "card-img-top" %>
    <% else %>
      <%= image_tag("no-event-image.png", class: "card-img-top") %>
    <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">タイトル：<%= @event.title %></h5>
        <p class="card-text">詳細：<%= @event.details %></p>
        <div class="parent-text d-flex justify-content-start border p-2">
        <div class="left-text">
        <p class="card-text">ジャンル：<%= @event.category.name %></p>
        <p class="card-text">開催エリア：<%= @event.event_prefecture.name %></p>
        <p class="card-text">参加可能人数：<%= @event.people_number.name %></p>
        <p class="card-text">参加費用：<%= @event.cost %>円</p>
            <% if current_user.already_favorited?(@event) %>
      <%= link_to event_favorites_path(@event), method: :delete, class: "text-decoration-none text-dark border-top mt-3" do %>
        <i class="fas fa-heart text-danger"></i>いいね！
      <% end %>
    <% else %>
      <%= link_to event_favorites_path(@event), method: :post, class: "text-decoration-none text-dark border-top mt-3" do %>
        <i class="far fa-heart text-danger"></i>いいね！
      <% end %>
    <% end %>
    <%= @event.favorites.count %>
        </div>
        <div class="right-text ms-5">
        <p class="card-text">イベント日時：<%= @event.event_date %></p>
        <p class="card-text">開始時間：<%= @event.start_time %></p>
        <p class="card-text">終了時間：<%= @event.end_time %></p>
        <p>現在のエントリー者数：<%= @event.entries.count %></p>
          <%= link_to  user_path(@event.user), method: :get, class: "text-decoration-none" do %>
        <p class="card-text"><small class="text-muted">主催者：<%= @event.user.nickname %></small></p>
          <% end %>
        <% if @event.user.id == current_user.id %>
          <%= link_to "編集", edit_event_path(@event), class: "btn btn-primary col-4 offset-4 mt-3" %>
        <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <% unless @event.entries.map(&:user_id).include? current_user.id or @event.user_id == current_user.id  %>
    <div class="d-flex justify-content-center">
      <%= link_to 'このイベントにエントリー', new_event_entry_path(@event.id), method: :get , class: "btn btn-info nav-link text-dark col-3" %>
    </div>
    <div class="text-center mb-5">
    <p>※（エントリーキャンセルについては主催者へチャットでご連絡ください。）</p>
  </div>
  <% end %>

  <% if @event.entries.map(&:user_id).include? current_user.id  %>
    <h5 class="text-center"><span class="badge bg-danger">エントリー済み</span></h5>
    <div class="text-center mb-5">
    <p>※（エントリーキャンセルについては主催者へチャットでご連絡ください。）</p>
  </div>
  <% end %>

  <div class="rounded border border-3 border-dark mt-5 p-5 col-8 mx-auto bg-white">
    <div class="comments">
      <div class="border-bottom border-2 mb-3 p-2"><h4>＜コメント一覧＞</h4></div>
      <% if @comments.blank? %>
        <p class="my-3"><small class="text-muted">※ まだコメントはありません。</small></p>
      <% else %>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <%= form_with(model: [@event, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "form-control col-3" %>
        <%= form.submit "送信", class: "mt-2 mb-5 px-4" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>

  <% if @event.user_id == current_user.id %>
  <div class="text-center border-top border-3 mt-5 pt-3">
    <h4>＜エントリー者一覧＞</h4>
    <p class="ms-3">現在のエントリー者数：<%= @event.entries.count %></p>
  <% @entrys.each do |entry| %>
    <% if entry.event_id == @event.id %>
      <div class="border p-2 my-2">
          <%= link_to user_path(entry.user_id), method: :get do %>
          <%= entry.j_family_name %>
          <%= entry.j_last_name %>さん
        <% end %>
          <span class="mx-1">学部：<%= entry.entry_undergraduate %></span>
          <span class="mx-1">性別：<%= entry.sex %></span>
          <span class="mx-1">学年：<%= entry.entry_school_year %></span>
          <br>
          あなたへのコメント：<%= entry.entry_comment %>
      </div>
    <% end %>
  <% end %>
  </div>
  <% end %>

</div>
</div>