config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'home#top'
  resources :users
  resources :events do
    resources :comments, only: :create
    resources :entries, only: [:index, :new, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  resources :notifications
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>FreeO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2f68b93d9f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  </head>

  <body>

    <header>
    <div class="notifications">
      <div class="notice"></div>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>
    </div>
<nav class="navbar navbar-expand-lg bg-light border border-secondary">
  <div class="container-fluid">
    <b><%= link_to '近大 Events', root_path , class: "navbar-brand text-decoration-none font-italic p-2 rounded-pill" %></b>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to 'ホーム', root_path, class: "nav-link active ms-1 text-dark" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'イベント', events_path, method: :get , class: "nav-link ms-1 text-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to 'イベント投稿', new_event_path, method: :get, class: "nav-link ms-1 text-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ユーザー一覧', users_path, method: :get, class: "nav-link ms-1 text-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path , method: :delete , class: "nav-link ms-1 text-dark" %>
        </li>
        <li class="nav-item">
          <%= link_to notifications_path, method: :get, class: "nav-link ms-3 text-dark me-2" do %>
            <i class="far fa-bell fa-lg"></i>          
            <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: orange;"></i>
          <% end %>
          <% end %>

        </li>
        <li class="nav-item">
          <%= link_to user_path(current_user), method: :get, class: "nav-link ms-3 text-dark" do %>
            <i class="far fa-user fa-lg"></i>
          <% end %>
        </li>
      </ul>
    </div>
        <% else %>
          <%= link_to 'イベント', events_path, class: "nav-link ms-1 text-dark" %>
          <%= link_to 'ユーザー一覧', users_path , method: :get, class: "nav-link ms-1 text-dark" %>
          <%= link_to '新規登録', new_user_registration_path , method: :get, class: "nav-link ms-1 text-dark" %>
          <%= link_to 'ログイン', new_user_session_path, method: :get, class: "nav-link ms-1 text-dark" %>
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "login nav-link ms-1 text-dark border border-info" %>
        <% end %>
      </div>
    </div>  
  </div>
</nav>
    <%= yield %>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>